name: Credenza CI

on:
  push:
    branches: 
      - main
      - '**'
  pull_request:
    branches:
      - main
      - '**'

jobs:
  build-and-test-contracts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
    
      - name: Install Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.11.3"

      - name: Install asdf
        uses: asdf-vm/actions/setup@v3

      - name: Install Starknet Foundry
        run: |
          asdf plugin add starknet-foundry || true
          asdf install starknet-foundry 0.41.0
          asdf global starknet-foundry 0.41.0
      - name: Build and Test Contracts
        run: |
          scarb build
          scarb test
          scarb fmt --check
